version: '3'
services:
  php:
    container_name: moodle
    build: moodle
    volumes:
      - ./moodle:/var/www/html/moodle
      - ./dockerfiles/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - moodle-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - moodle-network
volumes:
  mysql_data:
networks:
  moodle-network:
    name: moodle
    driver: bridge
